=== isabella87/banhuitong/src/main/resources/report_schme.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified">

	<xsd:element name="reportlist">	
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="reportItem" minOccurs="1" maxOccurs="10000">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="auId" type="xsd:long"/>
							<xsd:element name="loginName" type="xsd:string"/>
							<xsd:element name="realName" type="xsd:string"/>
							<xsd:element name="mobile" type="xsd:string"/>
							<xsd:element name="desc" type="xsd:string"/>
							
							<!-- <xsd:element name="fieldItem" type="fieldItemType" minOccurs="4" maxOccurs="5"/> -->
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
		
	<xsd:complexType name="fieldItemType">
		<xsd:sequence>
			<xsd:element name="fieldName" type="xsd:string"/>
			<xsd:element name="fieldValue" type="xsd:string"/>
			<xsd:element name="fieldType" type="fieldType"/>
		</xsd:sequence>
	</xsd:complexType>	
		
    <xsd:simpleType name="fieldType">
        <xsd:restriction base="xsd:normalizedString">
            <xsd:enumeration value="string"/>
            <xsd:enumeration value="integer"/>
            <xsd:enumeration value="decimal"/>
            <xsd:enumeration value="datetime"/>
            <xsd:enumeration value="double"/>
            <xsd:enumeration value="boolean"/>
            <xsd:enumeration value="binary"/>
        </xsd:restriction>
    </xsd:simpleType>
	
</xsd:schema>

=== isabella87/banhuitong/src/main/resources/report.xml
<?xml version="1.0" encoding="UTF-8" ?>

<reportlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="report_schme.xsd">

	<reportItem>
		<auId>434102</auId>
		<loginName>lb7688t</loginName>
		<realName>lb7688t</realName>
		<mobile>18307057688</mobile>
		<desc></desc>
	</reportItem>

	<reportItem>
		<auId>434103</auId>
		<loginName>duo549715346</loginName>
		<realName>duo549715346</realName>
		<mobile>18291984880</mobile>
		<desc></desc>
	</reportItem>
	
</reportlist>
